/*
 * BackgroundPanel.java
 *
 * Created on 05/04/2010, 23:22:23
 */

package r2d2e.solution.moduloteste.view;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.openide.util.Exceptions;

/**
 *
 * @author Rivaldo Jr
 */
public class BackgroundPanel extends javax.swing.JPanel {

    BufferedImage background;

    /** Creates new form BackgroundPanel */
    public BackgroundPanel() {
        initComponents();

        try {
            background = ImageIO.read(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/background.jpg"));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }

    }


    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(background, 0, 0,getWidth(),getHeight() ,null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
