/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfControle.java
 *
 * Created on 07/04/2010, 15:17:01
 */
package r2d2e.solution.moduloteste.view;

import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import r2d2e.solution.moduloteste.controlers.Controller;
import r2d2e.solution.moduloteste.controlers.PController;
import r2d2e.solution.moduloteste.controlers.PDController;
import r2d2e.solution.moduloteste.controlers.PIController;
import r2d2e.solution.moduloteste.controlers.PID2Controller;
import r2d2e.solution.moduloteste.controlers.PIDController;
import r2d2e.solution.moduloteste.handler.ControlModeHandler;

/**
 *
 * @author Rivaldo Jr
 */
public class ConfControle extends javax.swing.JPanel {

    private double sampleRate = 0.1;
    private ControlModeHandler controlModeHandler;

    /** Creates new form ConfControle */
    public ConfControle() {
        initComponents();
        popularComboBox();
        setP();
        controlModeHandler = new ControlModeHandler(this);
        controlModeHandler.setControllerSelected((Controller) comboControladores.getItemAt(0));
    }

    public void popularComboBox() {
        Vector<Controller> controllers = new Vector<Controller>();

        controllers.add(new PController(sampleRate, (Double) textSetPoint.getValue()));
        controllers.add(new PDController(sampleRate, (Double) textSetPoint.getValue()));
        controllers.add(new PIController(sampleRate, (Double) textSetPoint.getValue()));
        controllers.add(new PIDController(sampleRate, (Double) textSetPoint.getValue()));
        controllers.add(new PID2Controller(sampleRate, (Double) textSetPoint.getValue()));

        DefaultComboBoxModel boxModel = new DefaultComboBoxModel(controllers);

        comboControladores.setModel(boxModel);
        comboControladores.setSelectedIndex(0);

    }

    public void setP() {

        labelKd.setVisible(false);
        labelKi.setVisible(false);
        textKD.setVisible(false);
        textKI.setVisible(false);

    }

    public void setPD() {

        labelKd.setVisible(true);
        labelKi.setVisible(false);
        textKD.setVisible(true);
        textKI.setVisible(false);
    }

    public void setPI() {

        labelKi.setVisible(true);
        labelKd.setVisible(false);
        textKI.setVisible(true);
        textKD.setVisible(false);

    }

    public void setPID() {

        labelKd.setVisible(true);
        labelKi.setVisible(true);
        textKD.setVisible(true);
        textKI.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboControladores = new javax.swing.JComboBox();
        labelTipoCtrl = new javax.swing.JLabel();
        labelSetPoint = new javax.swing.JLabel();
        textSetPoint = new javax.swing.JFormattedTextField();
        panelGanhos = new javax.swing.JPanel();
        labelKp = new javax.swing.JLabel();
        labelKd = new javax.swing.JLabel();
        labelKi = new javax.swing.JLabel();
        textKI = new javax.swing.JFormattedTextField();
        textKD = new javax.swing.JFormattedTextField();
        textKP = new javax.swing.JFormattedTextField();
        SeparatorCtrl = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(540, 121));

        comboControladores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboControladoresItemStateChanged(evt);
            }
        });

        labelTipoCtrl.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoCtrl.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.labelTipoCtrl.text")); // NOI18N

        labelSetPoint.setForeground(new java.awt.Color(255, 255, 255));
        labelSetPoint.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.labelSetPoint.text")); // NOI18N

        textSetPoint.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textSetPoint.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSetPoint.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.textSetPoint.text")); // NOI18N

        panelGanhos.setBackground(new java.awt.Color(0, 0, 0));
        panelGanhos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.panelGanhos.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        labelKp.setForeground(new java.awt.Color(255, 255, 255));
        labelKp.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.labelKp.text")); // NOI18N

        labelKd.setForeground(new java.awt.Color(255, 255, 255));
        labelKd.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.labelKd.text")); // NOI18N

        labelKi.setForeground(new java.awt.Color(255, 255, 255));
        labelKi.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.labelKi.text")); // NOI18N

        textKI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textKI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textKI.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.textKI.text")); // NOI18N

        textKD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textKD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textKD.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.textKD.text")); // NOI18N

        textKP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textKP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textKP.setText(org.openide.util.NbBundle.getMessage(ConfControle.class, "ConfControle.textKP.text")); // NOI18N

        javax.swing.GroupLayout panelGanhosLayout = new javax.swing.GroupLayout(panelGanhos);
        panelGanhos.setLayout(panelGanhosLayout);
        panelGanhosLayout.setHorizontalGroup(
            panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKp)
                    .addComponent(labelKd)
                    .addComponent(labelKi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textKI, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(textKD, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(textKP, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGanhosLayout.setVerticalGroup(
            panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanhosLayout.createSequentialGroup()
                .addGroup(panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKp)
                    .addComponent(textKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKd)
                    .addComponent(textKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGanhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKi)
                    .addComponent(textKI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SeparatorCtrl.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelTipoCtrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboControladores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelSetPoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textSetPoint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addComponent(SeparatorCtrl, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(panelGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipoCtrl)
                        .addGap(11, 11, 11)
                        .addComponent(comboControladores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSetPoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSetPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeparatorCtrl, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboControladoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboControladoresItemStateChanged
        // TODO add your handling code here:
        Controller c = (Controller) comboControladores.getSelectedItem();
        if (c instanceof PController) {
            setP();
        }
        if (c instanceof PDController) {
            setPD();
        }
        if (c instanceof PIController) {
            setPI();
        }
        if (c instanceof PIDController || c instanceof PID2Controller) {
            setPID();
        }
        controlModeHandler.setControllerSelected(c);
    }//GEN-LAST:event_comboControladoresItemStateChanged

    public static void main(String args[]) {
        ConfControle ct = new ConfControle();
        JFrame frame = new JFrame();
        frame.add(ct);
        frame.setSize(540, 121);
        frame.setVisible(true);
    }

    ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparatorCtrl;
    private javax.swing.JComboBox comboControladores;
    private javax.swing.JLabel labelKd;
    private javax.swing.JLabel labelKi;
    private javax.swing.JLabel labelKp;
    private javax.swing.JLabel labelSetPoint;
    private javax.swing.JLabel labelTipoCtrl;
    private javax.swing.JPanel panelGanhos;
    private javax.swing.JFormattedTextField textKD;
    private javax.swing.JFormattedTextField textKI;
    private javax.swing.JFormattedTextField textKP;
    private javax.swing.JFormattedTextField textSetPoint;
    // End of variables declaration//GEN-END:variables
}
