package r2d2e.solution.moduloteste.view;

import java.awt.Dimension;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import r2d2e.solution.moduloteste.domain.graph.ModoVisualizacao;

/**
 *
 * @author Rivaldo Jr
 */
public class Modo3 extends JPanel implements ModoVisualizacao {

    private JPanel graphs[];

    /** Creates new form TestePanel */
    public Modo3() {
        initComponents();
        graphs = new JPanel[]{graph1, graph2, graph3};
    }

    public void addChart(int ix, ChartPanel chart) {

        if(ix > 2) {
            return;
        }

        chart.setPreferredSize(graphs[ix].getSize());
        chart.setSize(graphs[ix].getSize());

        graphs[ix].removeAll();
        graphs[ix].add(chart);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph1 = new javax.swing.JPanel();
        graph2 = new javax.swing.JPanel();
        graph3 = new javax.swing.JPanel();

        setOpaque(false);

        graph1.setBackground(new java.awt.Color(102, 153, 255));
        graph1.setOpaque(false);

        graph2.setBackground(new java.awt.Color(102, 153, 255));
        graph2.setOpaque(false);

        graph3.setBackground(new java.awt.Color(102, 153, 255));
        graph3.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graph2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graph3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graph2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(graph3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graph1;
    private javax.swing.JPanel graph2;
    private javax.swing.JPanel graph3;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        for (JPanel jPanel : graphs) {
            jPanel.removeAll();
        }
    }

}
