package r2d2e.solution.moduloteste.view;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;
import r2d2e.solution.moduloteste.handler.MainFrameHandler;

/**
 *
 * @author Rivaldo Jr
 */
public class NovoFrame extends javax.swing.JFrame {

    private MainFrameHandler mainFrameHandler = new MainFrameHandler(null); // NULL Por enquanto

    public NovoFrame() {
        initComponents();
        SkinInitialize();
    }

    private static void SkinInitialize() {
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);

        try { /*SubstanceBusinessLookAndFeel()*/
            UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
        } catch (Exception e) {
            System.out.println("Substance Raven Graphite failed to initialize");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new r2d2e.solution.moduloteste.view.BackgroundPanel();
        toolbarPanel = new javax.swing.JPanel();
        buttonIniciarTeste = new javax.swing.JButton();
        buttonNovoCiclo = new javax.swing.JButton();
        buttonPararTeste = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        buttonOpcoesGrafico = new javax.swing.JButton();
        buttonOpcoesGeral = new javax.swing.JButton();
        tanquePanel = new r2d2e.solution.moduloteste.view.TanquePanel();
        mainPanel = new javax.swing.JPanel();
        testePanel1 = new r2d2e.solution.moduloteste.view.TestePanel();
        opcoesPanel = new javax.swing.JPanel();
        confPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerTI = new javax.swing.JSpinner();
        spinnerTMax = new javax.swing.JSpinner();
        spinnerNA = new javax.swing.JSpinner();
        spinnerTMin = new javax.swing.JSpinner();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbarPanel.setOpaque(false);

        buttonIniciarTeste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/play_1.png"))); // NOI18N
        buttonIniciarTeste.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonIniciarTeste.toolTipText")); // NOI18N
        buttonIniciarTeste.setBorder(null);
        buttonIniciarTeste.setBorderPainted(false);
        buttonIniciarTeste.setContentAreaFilled(false);
        buttonIniciarTeste.setFocusable(false);
        buttonIniciarTeste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonIniciarTeste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonNovoCiclo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/play-repeat.png"))); // NOI18N
        buttonNovoCiclo.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonNovoCiclo.toolTipText")); // NOI18N
        buttonNovoCiclo.setBorder(null);
        buttonNovoCiclo.setBorderPainted(false);
        buttonNovoCiclo.setContentAreaFilled(false);
        buttonNovoCiclo.setFocusable(false);
        buttonNovoCiclo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNovoCiclo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonPararTeste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/play-stop.png"))); // NOI18N
        buttonPararTeste.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonPararTeste.toolTipText")); // NOI18N
        buttonPararTeste.setBorder(null);
        buttonPararTeste.setBorderPainted(false);
        buttonPararTeste.setContentAreaFilled(false);
        buttonPararTeste.setFocusable(false);
        buttonPararTeste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPararTeste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonOpcoesGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/statics-2.png"))); // NOI18N
        buttonOpcoesGrafico.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonOpcoesGrafico.toolTipText")); // NOI18N
        buttonOpcoesGrafico.setBorder(null);
        buttonOpcoesGrafico.setBorderPainted(false);
        buttonOpcoesGrafico.setContentAreaFilled(false);
        buttonOpcoesGrafico.setFocusable(false);
        buttonOpcoesGrafico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOpcoesGrafico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonOpcoesGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/tools.png"))); // NOI18N
        buttonOpcoesGeral.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonOpcoesGeral.toolTipText")); // NOI18N
        buttonOpcoesGeral.setBorder(null);
        buttonOpcoesGeral.setBorderPainted(false);
        buttonOpcoesGeral.setContentAreaFilled(false);
        buttonOpcoesGeral.setFocusable(false);
        buttonOpcoesGeral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOpcoesGeral.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonIniciarTeste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNovoCiclo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPararTeste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOpcoesGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOpcoesGeral)
                .addContainerGap(640, Short.MAX_VALUE))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOpcoesGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpcoesGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonPararTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNovoCiclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonIniciarTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        buttonIniciarTeste.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonIniciarTeste.AccessibleContext.accessibleDescription")); // NOI18N
        buttonNovoCiclo.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonNovoCiclo.AccessibleContext.accessibleDescription")); // NOI18N
        buttonPararTeste.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonPararTeste.AccessibleContext.accessibleDescription")); // NOI18N
        buttonOpcoesGrafico.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonOpcoesGrafico.AccessibleContext.accessibleDescription")); // NOI18N
        buttonOpcoesGeral.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.buttonOpcoesGeral.AccessibleContext.accessibleDescription")); // NOI18N

        tanquePanel.setOpaque(false);

        javax.swing.GroupLayout tanquePanelLayout = new javax.swing.GroupLayout(tanquePanel);
        tanquePanel.setLayout(tanquePanelLayout);
        tanquePanelLayout.setHorizontalGroup(
            tanquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        tanquePanelLayout.setVerticalGroup(
            tanquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        testePanel1.setOpaque(false);
        mainPanel.add(testePanel1, "card2");

        opcoesPanel.setOpaque(false);
        opcoesPanel.setLayout(new java.awt.CardLayout());

        confPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.confPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        confPanel.setOpaque(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jLabel8.text")); // NOI18N

        spinnerTI.setModel(new javax.swing.SpinnerNumberModel(0.0, 0.0, 3.0, 0.1));
        spinnerTI.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.spinnerTI.toolTipText")); // NOI18N
        spinnerTI.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerTI, "#,##0.0#"));

        spinnerTMax.setModel(new javax.swing.SpinnerNumberModel(1.0, 0.0, 3.0, 0.1));
        spinnerTMax.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.spinnerTMax.toolTipText")); // NOI18N
        spinnerTMax.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerTMax, "#,##0.0#"));

        spinnerNA.setModel(new javax.swing.SpinnerNumberModel(0.0, 0.0, 30.0, 0.1));
        spinnerNA.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.spinnerNA.toolTipText")); // NOI18N
        spinnerNA.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerNA, "#,##0.0#"));

        spinnerTMin.setModel(new javax.swing.SpinnerNumberModel(1.0, 0.0, 3.0, 0.1));
        spinnerTMin.setToolTipText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.spinnerTMin.toolTipText")); // NOI18N
        spinnerTMin.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerTMin, "#,##0.0#"));

        javax.swing.GroupLayout confPanelLayout = new javax.swing.GroupLayout(confPanel);
        confPanel.setLayout(confPanelLayout);
        confPanelLayout.setHorizontalGroup(
            confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerNA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerTI, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(spinnerTMax, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(spinnerTMin, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)))
        );
        confPanelLayout.setVerticalGroup(
            confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
            .addGroup(confPanelLayout.createSequentialGroup()
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinnerTMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinnerTMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(spinnerTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)))
        );

        opcoesPanel.add(confPanel, "card2");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tanquePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(toolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanquePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opcoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jMenu1.text")); // NOI18N
        menuBar.add(jMenu1);

        jMenu2.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jMenu2.text")); // NOI18N

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jCheckBoxMenuItem1.text")); // NOI18N
        jMenu2.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jCheckBoxMenuItem2.text")); // NOI18N
        jMenu2.add(jCheckBoxMenuItem2);

        menuBar.add(jMenu2);

        jMenu3.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.jMenu3.text")); // NOI18N

        itemSobre.setText(org.openide.util.NbBundle.getMessage(NovoFrame.class, "NovoFrame.itemSobre.text")); // NOI18N
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        jMenu3.add(itemSobre);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        About about = new About(this, true);
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private r2d2e.solution.moduloteste.view.BackgroundPanel backgroundPanel;
    private javax.swing.JButton buttonIniciarTeste;
    private javax.swing.JButton buttonNovoCiclo;
    private javax.swing.JButton buttonOpcoesGeral;
    private javax.swing.JButton buttonOpcoesGrafico;
    private javax.swing.JButton buttonPararTeste;
    private javax.swing.JPanel confPanel;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel opcoesPanel;
    private javax.swing.JSpinner spinnerNA;
    private javax.swing.JSpinner spinnerTI;
    private javax.swing.JSpinner spinnerTMax;
    private javax.swing.JSpinner spinnerTMin;
    private r2d2e.solution.moduloteste.view.TanquePanel tanquePanel;
    private r2d2e.solution.moduloteste.view.TestePanel testePanel1;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables

}
