package r2d2e.solution.moduloteste.view;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.openide.util.Exceptions;

/**
 *
 * @author Rivaldo Jr
 */
public class TanquePanel extends javax.swing.JPanel {

    private BufferedImage tanques;
    private BufferedImage waterImage1;
    private BufferedImage waterImage2;

    private double heightWater = 0;

    private int maxWidthWater1;
    private int maxWidthWater2;

    private int maxLevelWater = 30;

    /** Creates new form TanquePanel */
    public TanquePanel() {
        initComponents();
        loadImage();
    }

    @Override
    public void paint(Graphics g) {
        g.drawImage(tanques, 0, 0, null);
        g.drawImage(waterImage1,174, 14, null);
        g.drawImage(waterImage2,112, 253, null);

        g.drawImage(waterImage1, 174, 62 + (int)(maxWidthWater1-heightWater), waterImage1.getWidth(), (int)heightWater, null);
    }

    public void setLevelWater1(double levelWater) {
        double PercentWater = (100*levelWater)/maxLevelWater;
        heightWater = (PercentWater * maxWidthWater1) / 100;
        repaint();
    }

    public void setLevelWater2(double levelWater) {
        double PercentWater = (100*levelWater)/maxLevelWater;
        heightWater = (PercentWater * maxWidthWater2) / 100;
        repaint();
    }

    private void loadImage() {
        try {
            tanques = ImageIO.read(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/tanques.png"));
            waterImage1 = ImageIO.read(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/agua.png"));
            waterImage2 = ImageIO.read(getClass().getResource("/r2d2e/solution/moduloteste/view/resources/agua.png"));

            maxWidthWater1 = waterImage1.getHeight();
            maxWidthWater2 = waterImage1.getHeight();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
