/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmptyPanel.java
 *
 * Created on 24/10/2010, 21:31:53
 */

package br.ufrn.controle.fuzzycontroller.view.retractable;

import br.ufrn.controle.fuzzycontroller.shared.ConstantsFuzzy;
import br.ufrn.siga.component.retractable.RetractablePanelContent;

/**
 *
 * @author demetrios
 */
public class EmptyPanel extends javax.swing.JPanel implements RetractablePanelContent {

    private boolean compact;
    
    /** Creates new form EmptyPanel */
    public EmptyPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSetPoint = new javax.swing.JPanel();
        lblSetPoint = new javax.swing.JLabel();
        txtSetPoint = new javax.swing.JFormattedTextField();
        buttonSetPoint = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        panelSetPoint.setOpaque(false);
        panelSetPoint.setLayout(new java.awt.BorderLayout(10, 0));

        lblSetPoint.setText("SetPoint :");
        panelSetPoint.add(lblSetPoint, java.awt.BorderLayout.WEST);

        txtSetPoint.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSetPoint.setText("15.00");
        panelSetPoint.add(txtSetPoint, java.awt.BorderLayout.CENTER);

        buttonSetPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/controle/fuzzycontroller/view/resources/reload.png"))); // NOI18N
        buttonSetPoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        buttonSetPoint.setContentAreaFilled(false);
        buttonSetPoint.setFocusPainted(false);
        buttonSetPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetPointActionPerformed(evt);
            }
        });
        panelSetPoint.add(buttonSetPoint, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.insets = new java.awt.Insets(0, 54, 0, 54);
        add(panelSetPoint, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSetPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetPointActionPerformed
        // TODO add your handling code here:
        ConstantsFuzzy.setPoint = Double.parseDouble(txtSetPoint.getText());
    }//GEN-LAST:event_buttonSetPointActionPerformed

    public void showCompact() {
        compact = true;
    }

    public void showFull() {
        compact = false;
    }

    public boolean isCompactView() {
        return compact;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSetPoint;
    private javax.swing.JLabel lblSetPoint;
    private javax.swing.JPanel panelSetPoint;
    private javax.swing.JFormattedTextField txtSetPoint;
    // End of variables declaration//GEN-END:variables

}
