/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParametroSugenoPanel.java
 *
 * Created on 23/11/2010, 21:58:27
 */
package br.ufrn.controle.fuzzycontroller.view;

import br.ufrn.controle.fuzzycontroller.domain.Expression;

/**
 *
 * @author demetrios
 */
public class ParametroSugenoPanel extends javax.swing.JPanel {

    private static final String LBL_STRING = "Parâmetro";
    private static final String LBL_STRING_OFFSET = "Offset :";
    private Expression expression;
    private String variable;

    /** Creates new form ParametroSugenoPanel */
    public ParametroSugenoPanel() {
        initComponents();
    }

    public ParametroSugenoPanel(Expression expression, String variable) {
        initComponents();

        this.expression = expression;
        this.variable = variable;

        Double value = null;

        if (variable.equals("")) {
            value = expression.getOffset();
        } else {
            value = expression.getConstant(variable);

        }
        setValue(value == null ? 0 : value);
    }

    private Double getValue() {
        return Double.parseDouble(txtParaValue.getText());
    }

    private void setValue(double value) {
        txtParaValue.setText(Double.toString(value));
    }

    public void setParameterNumber(int i) {
        lblParameter.setText(LBL_STRING + i + ":");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblParameter = new javax.swing.JLabel();
        txtParaValue = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        setOpaque(false);

        lblParameter.setText("jLabel1");

        txtParaValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtParaValue.setText("0.00");
        txtParaValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtParaValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtParaValueFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParameter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtParaValue, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblParameter)
                .addComponent(txtParaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtParaValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParaValueFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParaValueFocusGained

    private void txtParaValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParaValueFocusLost
        // TODO add your handling code here:
        Double value = getValue();
        if (value != null) {
            if (variable.equals("")) {
                expression.setOffset(value);
            } else {
                expression.addConstant(variable, value);
            }
            
            System.out.println("value " + value + " " + variable);
        } else {
            System.out.println("value nulo");
        }
    }//GEN-LAST:event_txtParaValueFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblParameter;
    private javax.swing.JTextField txtParaValue;
    // End of variables declaration//GEN-END:variables

    public void setOffsetName() {
        lblParameter.setText(LBL_STRING_OFFSET);
    }
}
