/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RuleEditorPanel.java
 *
 * Created on 17/11/2010, 18:43:09
 */
package br.ufrn.controle.fuzzycontroller.view;

import br.ufrn.controle.fuzzycontroller.domain.DataBase;
import br.ufrn.controle.fuzzycontroller.domain.Expression;
import br.ufrn.controle.fuzzycontroller.funcaopertinencia.FuncPertinence;
import br.ufrn.controle.fuzzycontroller.domain.FuzzyController;
import br.ufrn.controle.fuzzycontroller.domain.Rule;
import br.ufrn.controle.fuzzycontroller.domain.RuleBase;
import br.ufrn.controle.fuzzycontroller.domain.Sugeno;
import br.ufrn.controle.fuzzycontroller.shared.ConstantsFuzzy;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author allan
 */
public class RuleEditorPanel extends javax.swing.JPanel {

    private RuleBase regras;
    private DataBase baseDados;
    private ArrayList<String> dataTypeIn;
    private ArrayList<JList> listas = new ArrayList<JList>();
    private ArrayList<JCheckBox> chkNot = new ArrayList<JCheckBox>();
    private final String NONE = "None";

    public RuleEditorPanel() {
        initComponents();
    }

    /** Creates new form RuleEditorPanel
     * @param controller
     */
    public RuleEditorPanel(FuzzyController controller) {
        baseDados = controller.getInference().getDataBase();
        regras = controller.getInference().getRuleBase();
        dataTypeIn = controller.getDataInType();

        initComponents();
        init();
    }

    public void setController(FuzzyController controller) {
        baseDados = controller.getInference().getDataBase();
        regras = controller.getInference().getRuleBase();
        dataTypeIn = controller.getDataInType();

        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelIns = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listOut = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsitRules = new javax.swing.JList();
        panelButton = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText(org.openide.util.NbBundle.getMessage(RuleEditorPanel.class, "RuleEditorPanel.jCheckBox3.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(RuleEditorPanel.class, "RuleEditorPanel.jLabel2.text")); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        panelIns.setBackground(new java.awt.Color(255, 255, 255));
        panelIns.setLayout(new javax.swing.BoxLayout(panelIns, javax.swing.BoxLayout.LINE_AXIS));

        listOut.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(listOut);

        lsitRules.setModel(new DefaultListModel());
        lsitRules.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsitRulesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsitRules);

        panelButton.setBackground(new java.awt.Color(255, 255, 255));
        panelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 3, 5));

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/controle/fuzzycontroller/view/resources/adicionar.png"))); // NOI18N
        buttonAdd.setText(org.openide.util.NbBundle.getMessage(RuleEditorPanel.class, "RuleEditorPanel.buttonAdd.text")); // NOI18N
        buttonAdd.setBorderPainted(false);
        buttonAdd.setContentAreaFilled(false);
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddMouseExited(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        panelButton.add(buttonAdd);

        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/controle/fuzzycontroller/view/resources/alterar.gif"))); // NOI18N
        buttonRefresh.setText(org.openide.util.NbBundle.getMessage(RuleEditorPanel.class, "RuleEditorPanel.buttonRefresh.text")); // NOI18N
        buttonRefresh.setBorderPainted(false);
        buttonRefresh.setContentAreaFilled(false);
        buttonRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRefreshMouseExited(evt);
            }
        });
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        panelButton.add(buttonRefresh);

        buttonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/controle/fuzzycontroller/view/resources/cancel.png"))); // NOI18N
        buttonRemove.setText(org.openide.util.NbBundle.getMessage(RuleEditorPanel.class, "RuleEditorPanel.buttonRemove.text")); // NOI18N
        buttonRemove.setBorderPainted(false);
        buttonRemove.setContentAreaFilled(false);
        buttonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRemoveMouseEntered(evt);
            }
        });
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });
        panelButton.add(buttonRemove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIns, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(panelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelIns, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        Rule regra = new Rule();

        boolean inputValido = false;
        for (int i = 0; i < listas.size(); i++) {
            try {
                if (!listas.get(i).getSelectedValue().toString().equals(NONE)) {
                    regra.addPremise(dataTypeIn.get(i), chkNot.get(i).isSelected(), (FuncPertinence) listas.get(i).getSelectedValue());
                    inputValido = true;
                }
            } catch (NullPointerException ex) {
                continue;
            }
        }

        if (!inputValido) {
            return;
        }

        if (listOut.getSelectedValue() instanceof Expression) {
            regra.addFunctionOut(ConstantsFuzzy.VARIABLE_OUTPUT, jCheckBox3.isSelected(), (Expression) listOut.getSelectedValue());
        } else {
            regra.addFunctionOut(ConstantsFuzzy.VARIABLE_OUTPUT, jCheckBox3.isSelected(), (FuncPertinence) listOut.getSelectedValue());
        }

        regras.addRule(regra);

        ((DefaultListModel) lsitRules.getModel()).addElement(regra);
}//GEN-LAST:event_buttonAddActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        Rule regra = (Rule) lsitRules.getSelectedValue();

        boolean inputValido = false;
        for (int i = 0; i < listas.size(); i++) {
            if (!listas.get(i).getSelectedValue().toString().equals(NONE)) {
                regra.addPremise(dataTypeIn.get(i), chkNot.get(i).isSelected(), (FuncPertinence) listas.get(i).getSelectedValue());
                inputValido = true;
            }
        }

        if (!inputValido) {
            return;
        }

        if (listOut.getSelectedValue() instanceof Expression) {
            regra.addFunctionOut(ConstantsFuzzy.VARIABLE_OUTPUT, jCheckBox3.isSelected(), (Expression) listOut.getSelectedValue());
        } else {
            regra.addFunctionOut(ConstantsFuzzy.VARIABLE_OUTPUT, jCheckBox3.isSelected(), (FuncPertinence) listOut.getSelectedValue());
        }

        lsitRules.repaint();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void lsitRulesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsitRulesValueChanged
        Rule regra = (Rule) lsitRules.getSelectedValue();

        if (regra == null) {
            return;
        }

        for (int i = 0; i < listas.size(); i++) {
            FuncPertinence func = regra.getInputShape(dataTypeIn.get(i));
            listas.get(i).setSelectedValue(func, true);
        }

        FuncPertinence fp = regra.getOutPutShape(ConstantsFuzzy.VARIABLE_OUTPUT);
        if (fp == null) {
            listOut.setSelectedValue(regra.getOutPutExpression(ConstantsFuzzy.VARIABLE_OUTPUT), true);
        } else {
            listOut.setSelectedValue(fp, true);
        }

    }//GEN-LAST:event_lsitRulesValueChanged

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        Rule regra = (Rule) lsitRules.getSelectedValue();
        if (regra != null) {
            regras.getRules().remove(regra);
            ((DefaultListModel) lsitRules.getModel()).removeElement(regra);
            lsitRules.repaint();
        }
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseEntered
        buttonAdd.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonAddMouseEntered

    private void buttonRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRefreshMouseEntered
        buttonRefresh.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonRefreshMouseEntered

    private void buttonRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMouseEntered
        buttonRemove.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonRemoveMouseEntered

    private void buttonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseExited
        buttonAdd.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonAddMouseExited

    private void buttonRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRefreshMouseExited
        buttonRefresh.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonRefreshMouseExited

    private void criarPanelInput(String nomeInput) {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));
        panel.setBackground(new java.awt.Color(255, 255, 255));

        JLabel label = new JLabel("<html>Se <font color=red>" + nomeInput + "</font> é:</html>");
        JList lista = new JList(new DefaultListModel());

        JScrollPane scroll = new JScrollPane();
        scroll.setViewportView(lista);

        JCheckBox chkBox = new JCheckBox("Não");
        chkBox.setBackground(new java.awt.Color(255, 255, 255));

        panel.setPreferredSize(new Dimension(15, 15));

        if (baseDados.getIn(nomeInput) != null) {
            for (FuncPertinence func : baseDados.getIn(nomeInput)) {
                ((DefaultListModel) lista.getModel()).addElement(func);
            }
        }

        ((DefaultListModel) lista.getModel()).addElement(NONE);

        panel.add(label);
        panel.add(scroll);
        panel.add(chkBox);

        listas.add(lista);
        chkNot.add(chkBox);

        panelIns.add(panel);
    }

    private void init() {
        panelIns.removeAll();
        listas = new ArrayList<JList>();
        ((DefaultListModel) lsitRules.getModel()).removeAllElements();
        lsitRules.clearSelection();

        ((DefaultListModel) listOut.getModel()).removeAllElements();
        listOut.clearSelection();

        if (baseDados.getOut(ConstantsFuzzy.VARIABLE_OUTPUT) != null) {
            for (FuncPertinence func : baseDados.getOut(ConstantsFuzzy.VARIABLE_OUTPUT)) {
                ((DefaultListModel) listOut.getModel()).addElement(func);
            }
        } else {
            for (Expression exp : baseDados.getExpressionOut(ConstantsFuzzy.VARIABLE_OUTPUT)) {
                ((DefaultListModel) listOut.getModel()).addElement(exp);
            }
        }

        for (String string : dataTypeIn) {
            criarPanelInput(string);
        }

        for (Rule regra : regras.getRules()) {
            ((DefaultListModel) lsitRules.getModel()).addElement(regra);
        }
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RuleEditorPanel panel = new RuleEditorPanel(new MainView().getControllerSelected());
                JDialog dialog = new JDialog();
                dialog.add(panel);
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listOut;
    private javax.swing.JList lsitRules;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelIns;
    // End of variables declaration//GEN-END:variables
}
