/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainView.java
 *
 * Created on 01/04/2010, 15:29:53
 */
package r2d2e.solution.tanksimulator.view;

import java.io.File;
import java.io.PrintStream;
import javax.swing.JButton;
import r2d2e.solution.tanksimulator.tank.Tanks3DContainer;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;
import r2d2e.solution.tanksimulator.handler.MainViewHandler;
import r2d2e.solution.tanksimulator.domain.Logger;
import r2d2e.solution.tanksimulator.domain.QuanserDriver;
import r2d2e.solution.tanksimulator.domain.Simulation;
import r2d2e.solution.tanksimulator.domain.Simulation3d;
import r2d2e.solution.tanksimulator.domain.UpdateStatus;
import r2d2e.solution.tanksimulator.socket.QuanserServer;

/**
 *
 * @author demetrios
 */
public class MainView extends javax.swing.JFrame {

    private MainViewHandler handler;
    private QuanserServer server;
    private QuanserDriver driver;
    private Simulation3d simulation3d;
    private Tanks3DContainer tanks3d;
    private int port = 20081;
    private static int delay = 100;//milisegundos
    private static boolean isStopped = false;

    /** Creates new form mainView */
    public MainView() {
        initComponents();
        SkinInitialize();
        init();
        simulatorPanel.add(tanks3d);
        tanks3d.setSize(simulatorPanel.getPreferredSize());
        Splash.getInstance().finalizaSplash();
    }

    private void init() {
        tanks3d = new Tanks3DContainer();
        handler = new MainViewHandler(this);
        simulation3d = new Simulation3d(delay, tanks3d);
        driver = new QuanserDriver(simulation3d, handler);

        URL imgURL = getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/r2d2e.jpg");
        setIconImage(new ImageIcon(imgURL).getImage());

        setSize(getWidth(), getHeight() + 180);
        setLocationRelativeTo(null);

        UpdateStatus.setIcon(labelIcon);
        UpdateStatus.setText(labelText);

        UpdateStatus.setSensor1(textSensor1);
        UpdateStatus.setSensor2(textSensor2);
        UpdateStatus.setTensao(textTensao);
        UpdateStatus.setMainView(this);

        WriteFile();
    }

    public void WriteFile() {

        try {
            String pastaLog = "c:\\Logs-R2D2E";
            File diretorio = new File(pastaLog);
            diretorio.mkdir();

            String file = pastaLog + "\\log.txt";
            PrintStream ps = new PrintStream(file);
            System.setOut(ps);
            System.setErr(ps);

        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpTank = new javax.swing.JPopupMenu();
        chkAllowFlowOut1 = new javax.swing.JCheckBoxMenuItem();
        chkAllowFlowOut2 = new javax.swing.JCheckBoxMenuItem();
        botoesPanel = new javax.swing.JPanel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonAltconf = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        infoPanel = new javax.swing.JPanel();
        textSensor2 = new javax.swing.JTextField();
        textTensao = new javax.swing.JTextField();
        textSensor1 = new javax.swing.JTextField();
        labelTensao = new javax.swing.JLabel();
        labelSensor2 = new javax.swing.JLabel();
        labelSensor1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonPause = new javax.swing.JButton();
        buttonFlow2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        buttonFlow1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        contentPanel = new javax.swing.JPanel();
        simulatorPanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        statusPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        labelIcon = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        itemConf = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        chkAllowFlowOut1.setSelected(true);
        chkAllowFlowOut1.setText("Permitir Vazão de Saída");
        chkAllowFlowOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllowFlowOut1ActionPerformed(evt);
            }
        });
        popUpTank.add(chkAllowFlowOut1);

        chkAllowFlowOut2.setSelected(true);
        chkAllowFlowOut2.setText("Permitir Vazão de Saída");
        chkAllowFlowOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllowFlowOut2ActionPerformed(evt);
            }
        });
        popUpTank.add(chkAllowFlowOut2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("R2D2E - Tank Simulator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/play.png"))); // NOI18N
        buttonStart.setToolTipText("Iniciar Simulação");
        buttonStart.setBorderPainted(false);
        buttonStart.setContentAreaFilled(false);
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/play_stop.png"))); // NOI18N
        buttonStop.setToolTipText("Parar Simulação");
        buttonStop.setBorderPainted(false);
        buttonStop.setContentAreaFilled(false);
        buttonStop.setEnabled(false);
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        buttonAltconf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/signal.png"))); // NOI18N
        buttonAltconf.setToolTipText("Editar Configurações do simulador");
        buttonAltconf.setBorderPainted(false);
        buttonAltconf.setContentAreaFilled(false);
        buttonAltconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltconfActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textSensor2.setEditable(false);
        textSensor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSensor2.setText("0.0");
        textSensor2.setToolTipText("Leitura Instântanea do sensor 2 (em cm)");

        textTensao.setEditable(false);
        textTensao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textTensao.setText("0.0");
        textTensao.setToolTipText("Tensão sendo aplicada (em Volt)");

        textSensor1.setEditable(false);
        textSensor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSensor1.setText("0.0");
        textSensor1.setToolTipText("Leitura Instântanea do sensor 1 ( em cm)");

        labelTensao.setText("Tensão :");

        labelSensor2.setText("Sensor 2 :");

        labelSensor1.setText("Sensor 1 :");

        jLabel1.setText("cm.");

        jLabel2.setText("cm.");

        jLabel3.setText("V.");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(labelTensao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTensao, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSensor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSensor1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSensor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSensor2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textTensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelTensao)
                .addComponent(labelSensor1)
                .addComponent(jLabel1)
                .addComponent(textSensor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelSensor2)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(textSensor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/pause.png"))); // NOI18N
        buttonPause.setToolTipText("Pausar a simulação - Serve para simular o desligamento da potencia");
        buttonPause.setBorder(null);
        buttonPause.setBorderPainted(false);
        buttonPause.setContentAreaFilled(false);
        buttonPause.setEnabled(false);
        buttonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPauseActionPerformed(evt);
            }
        });

        buttonFlow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/tank_two_open.png"))); // NOI18N
        buttonFlow2.setToolTipText("Clique aqui para bloquear a vazão de saída do tanque 2");
        buttonFlow2.setBorder(null);
        buttonFlow2.setBorderPainted(false);
        buttonFlow2.setContentAreaFilled(false);
        buttonFlow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFlow2ActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonFlow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/tank_one_open.png"))); // NOI18N
        buttonFlow1.setToolTipText("Clique aqui para bloquear a vazão de saída do tanque 1");
        buttonFlow1.setBorder(null);
        buttonFlow1.setBorderPainted(false);
        buttonFlow1.setContentAreaFilled(false);
        buttonFlow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFlow1ActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout botoesPanelLayout = new javax.swing.GroupLayout(botoesPanel);
        botoesPanel.setLayout(botoesPanelLayout);
        botoesPanelLayout.setHorizontalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFlow1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFlow2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(buttonAltconf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botoesPanelLayout.setVerticalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buttonStart, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonPause, javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonStop, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonFlow1, javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(buttonFlow2, javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonAltconf, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(infoPanel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        simulatorPanel.setBackground(new java.awt.Color(255, 255, 255));
        simulatorPanel.setComponentPopupMenu(popUpTank);
        simulatorPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                simulatorPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout simulatorPanelLayout = new javax.swing.GroupLayout(simulatorPanel);
        simulatorPanel.setLayout(simulatorPanelLayout);
        simulatorPanelLayout.setHorizontalGroup(
            simulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        simulatorPanelLayout.setVerticalGroup(
            simulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/ball_blue.png"))); // NOI18N

        labelText.setFont(new java.awt.Font("Verdana", 0, 11));

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelText)
                .addContainerGap(611, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIcon)
                    .addComponent(labelText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(simulatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuFile.setText("Arquivo");

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/close.png"))); // NOI18N
        itemSair.setText("Sair");
        itemSair.setToolTipText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuFile.add(itemSair);

        menuBar.add(menuFile);

        menuEdit.setText("Editar");

        itemConf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        itemConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/settings20x20.png"))); // NOI18N
        itemConf.setText("Configurações");
        itemConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfActionPerformed(evt);
            }
        });
        menuEdit.add(itemConf);

        menuBar.add(menuEdit);

        menuHelp.setText("Ajuda");

        itemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r2d2e/solution/tanksimulator/view/resource/r2d2e20X20.jpg"))); // NOI18N
        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuHelp.add(itemSobre);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltconfActionPerformed
        // TODO add your handling code here:
        handler.editConfig();
    }//GEN-LAST:event_buttonAltconfActionPerformed

    private void itemConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfActionPerformed
        // TODO add your handling code here:
        handler.editConfig();
    }//GEN-LAST:event_itemConfActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // TODO add your handling code here:
        server.closeConnection();
        dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        isStopped = false;
        if (server == null || !server.isAlive()) {
            server = new QuanserServer(port, driver);
            server.start();
            simulation3d.start();
        }
        simulation3d.pause(false);
        buttonStop.setEnabled(true);
        buttonStart.setEnabled(false);
        buttonPause.setEnabled(true);
        buttonAltconf.setEnabled(false);
        Logger.println("----------------------------");
        Logger.println("Simulação Iniciada.");
        UpdateStatus.updateSatus(UpdateStatus.GREEN_STATUS, "Simulação Inciada.");
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        stop();
    }

    public void stop() {
        isStopped = true;
        // TODO add your handling code here:
        Logger.println("Simulação Parada.");
        Logger.println("----------------------------");
        server.setAtivo(false);
        server.closeAllConnections();
        server.closeConnection();
        driver.writeAtBomb("0", "0.0", 999);
        buttonStart.setEnabled(true);
        buttonStop.setEnabled(false);
        buttonPause.setEnabled(false);
        buttonAltconf.setEnabled(true);
        UpdateStatus.updateSatus(UpdateStatus.BLUE_STATUS, "Simulação Parada.");
    }//GEN-LAST:event_buttonStopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (server != null) {
            server.closeConnection();
        }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void chkAllowFlowOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllowFlowOut1ActionPerformed
        // TODO add your handling code here:
        boolean sel = chkAllowFlowOut1.isSelected();
        simulation3d.setAllowFlowOut1(sel);
        Logger.println(sel ? "O oríficio de saída do tanque 1 aberto" : "O oríficio de saída do tanque 1 fechado" + ".");
    }//GEN-LAST:event_chkAllowFlowOut1ActionPerformed

    private void chkAllowFlowOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllowFlowOut2ActionPerformed
        // TODO add your handling code here:
        boolean sel = chkAllowFlowOut2.isSelected();
        simulation3d.setAllowFlowOut2(sel);
        Logger.println(sel ? "O oríficio de saída do tanque 2 aberto" : "O oríficio de saída do tanque 2 fechado" + ".");
    }//GEN-LAST:event_chkAllowFlowOut2ActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        // TODO add your handling code here:
        About about = new About(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    private void simulatorPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_simulatorPanelComponentResized
        tanks3d.setSize(simulatorPanel.getSize());
        tanks3d.setCanvasSize(simulatorPanel.getSize());
    }//GEN-LAST:event_simulatorPanelComponentResized

    private void buttonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPauseActionPerformed
        // TODO add your handling code here:
        handler.pause();
    }//GEN-LAST:event_buttonPauseActionPerformed

    private void buttonFlow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFlow1ActionPerformed
        // TODO add your handling code here:
        handler.flow1();
    }//GEN-LAST:event_buttonFlow1ActionPerformed

    private void buttonFlow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFlow2ActionPerformed
        // TODO add your handling code here:
        handler.flow2();
    }//GEN-LAST:event_buttonFlow2ActionPerformed

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public Simulation3d getSimulation() {
        return simulation3d;
    }

    public void setSimulation(Simulation3d simulation3d) {
        this.simulation3d = simulation3d;
    }

    public JButton getButtonAltconf() {
        return buttonAltconf;
    }

    public void setButtonAltconf(JButton buttonAltconf) {
        this.buttonAltconf = buttonAltconf;
    }

    public JButton getButtonFlow1() {
        return buttonFlow1;
    }

    public void setButtonFlow1(JButton buttonFlow1) {
        this.buttonFlow1 = buttonFlow1;
    }

    public JButton getButtonFlow2() {
        return buttonFlow2;
    }

    public void setButtonFlow2(JButton buttonFlow2) {
        this.buttonFlow2 = buttonFlow2;
    }

    public JButton getButtonPause() {
        return buttonPause;
    }

    public void setButtonPause(JButton buttonPause) {
        this.buttonPause = buttonPause;
    }

    public JButton getButtonStart() {
        return buttonStart;
    }

    public void setButtonStart(JButton buttonStart) {
        this.buttonStart = buttonStart;
    }

    public JButton getButtonStop() {
        return buttonStop;
    }

    public void setButtonStop(JButton buttonStop) {
        this.buttonStop = buttonStop;
    }

    private static void SkinInitialize() {
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);

        try { /*SubstanceBusinessLookAndFeel()*/
            UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
        } catch (Exception e) {
            System.out.println("Substance Raven Graphite failed to initialize");
        }
    }

    public boolean isStarted() {
        return server.isAlive();
    }

    public static boolean isStopped() {
        return isStopped;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPanel;
    private javax.swing.JButton buttonAltconf;
    private javax.swing.JButton buttonFlow1;
    private javax.swing.JButton buttonFlow2;
    private javax.swing.JButton buttonPause;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JCheckBoxMenuItem chkAllowFlowOut1;
    private javax.swing.JCheckBoxMenuItem chkAllowFlowOut2;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JMenuItem itemConf;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelSensor1;
    private javax.swing.JLabel labelSensor2;
    private javax.swing.JLabel labelTensao;
    private javax.swing.JLabel labelText;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JPopupMenu popUpTank;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel simulatorPanel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField textSensor1;
    private javax.swing.JTextField textSensor2;
    private javax.swing.JTextField textTensao;
    // End of variables declaration//GEN-END:variables
}
