/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestePanel.java
 *
 * Created on 31/10/2010, 21:01:07
 */
package br.ufrn.controle.fuzzycontroller.teste;

import br.ufrn.siga.component.retractable.RetractablePanelContent;

/**
 *
 * @author demetrios
 */
public class TestePanel extends javax.swing.JPanel implements RetractablePanelContent{

    private boolean compact;

    /** Creates new form TestePanel */
    public TestePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cornerPanel1 = new br.ufrn.siga.component.corner.CornerPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addComponent(cornerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
            .addComponent(cornerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showCompact() {
        compact = true;
    }

    public void showFull() {
        compact = false;
    }

    public boolean isCompactView() {
        return compact;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ufrn.siga.component.corner.CornerPanel cornerPanel1;
    // End of variables declaration//GEN-END:variables
}
