/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teste.java
 *
 * Created on 21/10/2010, 10:15:58
 */
package br.ufrn.controle.fuzzycontroller.teste;

import br.ufrn.siga.component.retractable.RetractablePanelContent;

/**
 *
 * @author Demetrios
 */
public class Teste extends javax.swing.JFrame implements RetractablePanelContent {

    private boolean compact;

    /** Creates new form teste */
    public Teste() {
        initComponents();

    }

//    public void addValue(String tipo, double value) {
//        graph.addValue(tipo, value);
//    }
//
//    public void init() {
//        graph.init();
//    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cornerPanel1 = new br.ufrn.siga.component.corner.CornerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cornerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cornerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        final Teste e = new Teste();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                e.setVisible(true);
            }
        });


//        new Thread() {
//
//            @Override
//            public void run() {
//                double i = 1;
//                e.init();
//                while (true) {
//                    e.addValue(ConstantsGraph.NIVEL1, Math.sin(i));
//                    i++;
//
//                    try {
//                        sleep(100);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Teste.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//        }.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ufrn.siga.component.corner.CornerPanel cornerPanel1;
    // End of variables declaration//GEN-END:variables

    public void showCompact() {
        compact = true;
    }

    public void showFull() {
        compact = false;
    }

    public boolean isCompactView() {
        return compact;
    }
}
